# Set up and run this Streamlit App
import streamlit as st
#from bs4 import BeautifulSoup
from logics.webscrape import scraper
from logics.webscrape import reply
import pandas as pd
import numpy as np

#from logics.customer_query_handler import process_user_message
#from helper_functions import llm # <--- This is the helper function that we have created 🆕
#import json
#from helper_functions import llm

st.set_page_config(
    layout="centered",
    page_title="Career Advisor"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Career Advisor 🐷")
st.write ("Ask Ms Piggy for advice on your mid-career crisis. She will provide some information about the field\
          that you would like to transit into and provide some courses you can spend your skillsfuture credits on!")

expander = st.expander("IMPORTANT NOTICE")
expander.write('''
             This web application is a prototype developed for educational purposes only.\
             The information provided here is NOT intended for real-world usage and should not be relied upon\
             for making any decisions, especially those related to financial, legal, or healthcare matters.\n\
             Furthermore, please be aware that the LLM may generate inaccurate or incorrect information.\
            You assume full responsibility for how you use any generated output.\n\
            Always consult with qualified professionals for accurate and personalized advice.
''')

form = st.form(key="form")
form.subheader("Ask me!")

#st.sidebar.success("Select a demo above.")

links = ['https://www.myskillsfuture.gov.sg/content/portal/en/training-exchange/course-directory/course-detail.html?courseReferenceNumber=TGS-2020500290', 'https://www.myskillsfuture.gov.sg/content/portal/en/training-exchange/course-directory/course-detail.html?courseReferenceNumber=TGS-2018502754', 'https://www.myskillsfuture.gov.sg/content/portal/en/training-exchange/course-directory/course-detail.html?courseReferenceNumber=TGS-2024043624']
#coursedetails(links)
user_prompt = form.text_area("Enter your prompt here, continue \"I want a job in ..\"", height=70)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    reply(user_prompt)
    #response = process_user_message(user_prompt) # <--- This calls the helper function that we have created 🆕
    #st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    print(f"User Input is {user_prompt}")

# df = pd.DataFrame(
#     {
#         "col1": 200,
#         "col2": 5,
#     }
# ) 
# st.map(df, 
# latitude="col1", longitude="col2")



   